### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by ghost** [augustt0/sidebar_bigeagle#2]
When i implement the example, the google chrome will collapse with bunch of errors, and when i delete the code leaving only import, am getting this error "Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:sidebar_bigeagle"
![Screenshot (107)](https://user-images.githubusercontent.com/103434266/165048562-584d3563-faec-4cf9-b394-b88a855b5222.png)

**Comment by augustt0** [comment]
Hi @capt91 I'm so sorry for the delay, I've just updated the package to add Null Safety compatibility (version 0.2.1). Thank you!
